version: '3.1'

services:
  back:
    build: ./backend
    container_name: back
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - "8090:8090"
    volumes:
      - ./backend/:/code
    env_file:
      - ./.env
    depends_on:
      - database
    links:
      - database
    stdin_open: true
    tty: true
    networks:
      - app-network

  database:
    container_name: database
    image: postgres:latest
    volumes:
      - postgres_data_project:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - app-network

volumes:
  postgres_data_project:

networks:
  app-network:
