# Generated by Django 4.1.4 on 2022-12-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_place_address_place_address_comment_place_city_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='site',
            new_name='place',
        ),
    ]
