# Generated by Django 4.1.4 on 2022-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='updated_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
