# Generated by Django 4.1.4 on 2022-12-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_alter_answer_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='place',
            name='address_comment',
            field=models.TextField(blank=True, max_length=510, null=True, verbose_name='Address comment'),
        ),
        migrations.AddField(
            model_name='place',
            name='city_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City name'),
        ),
        migrations.AddField(
            model_name='place',
            name='country_name',
            field=models.CharField(choices=[('FRANCE', 'FRANCE')], default='FRANCE', max_length=50, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='place',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Zipcode'),
        ),
    ]
