# Generated by Django 4.1.4 on 2023-03-16 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_remove_comment_place_comment_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='place.place'),
        ),
    ]
