# Generated by Django 4.1.4 on 2023-03-16 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_option_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='place.place'),
        ),
    ]
