# Generated by Django 4.1.7 on 2023-05-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_remove_answer_date_answer_duration_answer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='duration',
        ),
    ]
