# Generated by Django 4.1.7 on 2023-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_remove_answer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Duration in days'),
        ),
    ]
