# Generated by Django 4.1.4 on 2023-01-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
