# Generated by Django 4.1.4 on 2023-03-14 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_remove_comment_place_comment_answer_and_more'),
        ('user', '0003_membership_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='place.place'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
