# Generated by Django 4.1.4 on 2023-03-14 17:23

from django.db import migrations
import user.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_membership_place_alter_membership_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', user.models.user.AppUserManager()),
            ],
        ),
    ]
