# Generated by Django 4.1.7 on 2023-03-17 14:02

from django.db import migrations
import user.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.user.AppUserManager()),
            ],
        ),
    ]
