# Generated by Django 4.1.7 on 2023-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('read_only', 'read only'), ('editor', 'editor'), ('admin', 'admin')], default='editor', max_length=200),
        ),
    ]
