# Generated by Django 4.1.7 on 2023-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('READ_ONLY', 'READ_ONLY'), ('EDITOR', 'EDITOR'), ('ADMIN', 'ADMIN')], default='EDITOR', max_length=200),
        ),
    ]
